from itertools import combinations

surnames = [
    "Příjmení",
    "Šembera",
    "Boháč",
    "Fabinger",
    "Havlas",
    "Jelínek",
    "Konrád",
    "Pokorný",
    "Řezníček",
    "Schmidt",
    "Vavřina",
    "Brodský",
    "Certin",
    "Herrmann",
    "Jícha",
    "Jirásek",
    "Ledvinka",
    "Lustig",
    "Musil",
    "Novák",
    "Novotný",
    "Postránecký",
    "Přibyslavský",
    "Říhánek",
    "Šulc",
    "Veselý",
    "Záhorský",
    "Baberkov",
    "Beneš",
    "Bláha",
    "Cenčić",
    "Diviš",
    "Dudek",
    "Ehrlich",
    "Fontán",
    "Grunt",
    "Hambálek",
    "Hartl",
    "Hassdenteufel",
    "Hauf",
    "Havlíček",
    "Houser",
    "Kabelík",
    "Karásek",
    "Karl",
    "Karlovský",
    "Kindl",
    "Kořínek",
    "Kraus",
    "Kulda",
    "Majcen",
    "Marván",
    "Rozsypal",
    "Sáblík",
    "Schier",
    "Schulz",
    "Schworm",
    "Smíšek",
    "Stjepanek",
    "Suchánek",
    "Svoboda",
    "Šícha",
    "Urbánek",
    "Vančura",
    "Vochoč",
]

# Generate all combinations of the surnames
surname_combinations = list(combinations(surnames, 2))

# Print the generated combinations
for combination in surname_combinations:
    print(combination)

